// harness/run-loading-screen.ts — anchor for the reusable LoadingScreen (ดวงสมพงศ์ Slice 2 · ก้อน 2D).
// LENS = visual/presentation. Ground-truth = the RENDERED page @393, not a prop or a className.
//
// The component's LOOK is lifted from Figma 375:20499 — a PAYMENT-PROCESSING screen. The whole point of
// 2D (D16) is that this shell carries the LOOK (cloud-sky BG01 + leaf mascot + centred stack) but NONE of
// that node's PAYMENT COPY ("กำลังดำเนินการชำระเงิน" / "Omise …"): title + subtitle are props, so the same
// loader serves any wait (per ฟีม's AMEND-1, D17's real compat-calc mount lands in 2E).
//
// Invariants owned here:
//   D16  no payment copy leak — the RENDERED text contains NEITHER "ชำระเงิน" NOR "Omise"; the only text is
//        the props passed in (+ the sr-only fallback). A recoloured-but-leaky loader is the bug.
//   D18  role="status" + aria-live="polite" present → a screen-reader user hears the wait on mount.
//   look — BG01 (byte-identical to the node's fill) + mascot-leaf both actually paint; console clean.
//
// TOOTH (proven live in loading-screen.verify-evidence.md):
//   • mut-payment-leak — hardcode the node's payment subtitle ("Omise กำลังยืนยันบัตรของคุณ") INTO
//     LoadingScreen.tsx (in addition to the prop). The D16 assertion (#no-payment-copy) then sees "Omise" in
//     the rendered text though the caller passed innocuous copy → CAUGHT. This is the exact D16 bug: the
//     payment screen's words riding along inside a "reusable" loader.
//
// VERIFY-THE-INSTRUMENT (negative control): #no-payment-copy is only evidence if it CAN fail. The tooth run
//   is that control — known-good (props only) reads clean; known-bad (mut-payment-leak) trips. A probe that
//   passes even when payment copy is present would be vacuous.
//
// Re-runnable + ships nothing extra: the anchor WRITES its own preview fixture (pages/_loading-preview.tsx),
// captures against a running dev server, then removes the fixture in `finally`. No preview route is committed.
// (Underscore prefix — NOT a dot prefix: a `pages/.x.tsx` chunk 400s in the Next dev server.)
//
// Run (dev up on :3021):  next dev -p 3021
//   npx tsx harness/run-loading-screen.ts
//   MUT=payment-leak npx tsx harness/run-loading-screen.ts   # expect the tooth to FAIL #no-payment-copy
import { chromium } from 'playwright'
import * as fs from 'fs'
import * as path from 'path'

const HOST = process.env.CAPTURE_HOST ?? 'http://localhost:3021'
const MUT = process.env.MUT ?? ''
const FIXTURE = path.resolve(process.cwd(), 'pages/_loading-preview.tsx')
const SHOT = path.resolve(process.cwd(), 'harness/pixel-proof/loading-2d-393.png')

const TITLE = 'กำลังคำนวณดวงสมพงศ์'
const SUBTITLE = 'กรุณาอย่าปิดหน้านี้ ระบบกำลังประมวลผล' // innocuous — NO payment words

let failed = 0
const check = (name: string, ok: boolean, detail = '') => {
  console.log(`  ${ok ? '✓' : '✗'} ${name}${detail ? `  — ${detail}` : ''}`)
  if (!ok) failed++
}

function writeFixture() {
  // mut-payment-leak: simulate the component leaking the payment node's copy by appending a hardcoded
  // "Omise …" line to the rendered subtitle. (The real bug is that copy living INSIDE the component; the
  // fixture reproduces the same observable — payment words in the rendered text the caller never asked for.)
  const leak = MUT === 'payment-leak'
    ? `<>{'${SUBTITLE}'}<br/>{'Omise กำลังยืนยันบัตรของคุณ'}</>`
    : `'${SUBTITLE}'`
  fs.writeFileSync(
    FIXTURE,
    `// AUTO-GENERATED by harness/run-loading-screen.ts — removed after the run. Do NOT commit.\n` +
      `import { LoadingScreen } from '@/features/v2-shell/components/LoadingScreen'\n` +
      `export default function LoadingPreview() {\n` +
      `  return <LoadingScreen title={'${TITLE}'} subtitle={${leak}} />\n` +
      `}\n`,
  )
}

async function main() {
  writeFixture()
  const browser = await chromium.launch()
  try {
    const ctx = await browser.newContext({
      viewport: { width: 393, height: 852 },
      deviceScaleFactor: 2,
      reducedMotion: 'reduce', // deterministic: motion-safe animations off → static resting pose
    })
    const page = await ctx.newPage()
    const consoleErrors: string[] = []
    page.on('console', (m) => { if (m.type() === 'error') consoleErrors.push(m.text()) })

    // dev may still be compiling the just-written fixture — retry the goto a few times
    let ok = false
    for (let i = 0; i < 12 && !ok; i++) {
      try {
        const res = await page.goto(`${HOST}/_loading-preview`, { waitUntil: 'networkidle', timeout: 8000 })
        ok = !!res && res.ok()
      } catch { /* recompiling */ }
      if (!ok) await page.waitForTimeout(1000)
    }
    check('preview route reachable', ok, `${HOST}/_loading-preview`)
    if (!ok) return

    await page.waitForTimeout(400)

    // D18 — announced region
    const roleStatus = await page.locator('[role="status"]').count()
    const ariaLive = await page.locator('[role="status"][aria-live="polite"]').count()
    check('D18 role=status present', roleStatus === 1, `count=${roleStatus}`)
    check('D18 aria-live=polite present', ariaLive === 1, `count=${ariaLive}`)

    // props render
    const title = (await page.locator('h1').first().innerText()).trim()
    check('title prop renders', title === TITLE, title)

    // look — bg + mascot actually paint
    const bg = await page.locator('img[src*="BG01"]').count()
    const mascot = await page.locator('img[src*="mascot-leaf"]').count()
    check('BG01 cloud-sky present', bg >= 1)
    check('mascot-leaf present', mascot >= 1)

    // D16 — the tooth. rendered text must carry NEITHER payment word.
    const bodyText = await page.locator('body').innerText()
    const leaks = /ชำระเงิน|Omise/.test(bodyText)
    check('#no-payment-copy (D16)', !leaks, leaks ? 'LEAK: payment copy in rendered text' : 'clean')

    // console clean (no data fetches in this component → any error is a real defect)
    check('console errors = 0', consoleErrors.length === 0, consoleErrors.join(' | '))

    if (MUT !== 'payment-leak') {
      await page.screenshot({ path: SHOT })
      console.log(`  📸 ${SHOT}`)
    }
  } finally {
    await browser.close()
    fs.rmSync(FIXTURE, { force: true }) // never commit the fixture
  }

  console.log(MUT ? `\n[MUT=${MUT}] failed=${failed} (tooth EXPECTED to fail #no-payment-copy)` : `\nfailed=${failed}`)
  // Under the mutant the run SHOULD fail (the tooth bites); a clean baseline SHOULD pass.
  process.exit(MUT ? (failed > 0 ? 0 : 1) : failed > 0 ? 1 : 0)
}

main().catch((e) => { fs.rmSync(FIXTURE, { force: true }); console.error(e); process.exit(1) })
