// #358 Phase 2 — the two calendar gates decide from ONE source.
//
// ANCHOR: scripts/calendar-gates-one-source.test.tsx#both-calendar-gates-agree-for-every-store-state
// Bug-class this owns: one feature, two server gates, two different stores. `pages/api/v2/day-detail.ts:82`
// has always asked `resolveSubscription` (member_subscription first, member_payment as the fallback);
// `pages/api/v2/calendar-month.ts` asked `resolveMembership` (member_payment and nothing else). Nothing in
// the codebase ever compared their answers, so the split was invisible from every direction: the board has
// no state for it, both routes had green tests, and no user was affected.
//
// 🔴 THE SHAPE OF THE TEST IS THE POINT. The stubs below model the two STORES — a member_subscription row
// and a member_payment row — and the two resolvers are reconstructed on top of them exactly as the real
// ones read them (lib/usage.ts:27 reads one table; lib/v2/subscription.ts:220-243 reads the other and then
// falls back to the first). The assertion is then AGREEMENT across every combination, which means the
// divergent state is GENERATED by the fixture rather than asserted by me. A test that hard-coded
// "v2-row-only ⇒ allowed" would be my belief about the resolvers wearing a green tick.
//
// ⚠️ WHAT THIS DOES NOT PROVE, and what does. The premise — that the real resolvers read the two stores
// this way — is modelled here, not measured here. It is measured against real postgres in
// `scripts/member-subscription-db.test.ts` ("#358 Phase 2 — the premise"), which is DB-gated and does not
// run in this lane. If those two files ever disagree, the DB one is right.
//
// 🔴 MUTANT CONTRACT (each reddens `npm test`):
//   Fired 2026-08-29 against the committed baseline, results as measured and not as predicted:
//   MP1  calendar-month goes back to resolveMembership   → ① v2-row-only + ④ redden (2 of 7). The other
//        three rows of ① stay green, which is what makes it the DIVERGENT state and not a blanket failure.
//   MP2  calendar-month reads `isPaid` loosely (`!== false` instead of `=== true`)  → ③ only (1 of 7)
//   MP3  day-detail goes to resolveMembership instead     → ① v2-row-only reddens from the other side
//        (1 of 7), proving the table watches both routes and not just the one that changed
import { describe, it, expect, vi, beforeEach } from 'vitest'

const h = vi.hoisted(() => ({
  who: { ok: true, userId: 'U' } as { ok: true; userId: string } | { ok: false; status: 401; error: string },
  // THE STORES. Everything below is derived from these two sets, never set directly.
  memberPaymentValid: new Set<string>(),
  liveV2Row: new Set<string>(),
  /** set to force the undetermined verdict — a v2 row whose tier_code we refused to understand. */
  undetermined: new Set<string>(),
}))

vi.mock('@/lib/v2/resolve-user', () => ({ resolveSessionUserId: vi.fn(async () => h.who) }))

// lib/usage.ts:27 — one table, one row, classify. Nothing else.
vi.mock('@/lib/usage', () => ({
  resolveMembership: vi.fn(async (userId: string) => ({
    isFree: !h.memberPaymentValid.has(userId),
    reason: h.memberPaymentValid.has(userId) ? 'MEMBER' : 'NO_PLAN',
    memberPayment: null,
  })),
}))

// lib/v2/subscription.ts:220-243 — the v2 rows decide when one is live; otherwise the legacy verdict.
vi.mock('@/lib/v2/subscription', () => ({
  resolveSubscription: vi.fn(async (userId: string) => {
    if (h.undetermined.has(userId)) return { isPaid: null, tier: null, source: 'v2', expireAt: null }
    if (h.liveV2Row.has(userId)) return { isPaid: true, tier: 'PRO', source: 'v2', expireAt: null }
    const legacy = h.memberPaymentValid.has(userId)
    return {
      isPaid: legacy,
      tier: legacy ? 'PRO' : null,
      source: legacy ? 'legacy' : 'none',
      expireAt: null,
    }
  }),
}))

// Only the upstream network is stubbed. The gate switch (lib/v2-calendar/gate) is deliberately NOT mocked,
// so this exercises the value that actually ships — the same choice scripts/calendar-month-gate-closed.tsx
// makes, and for the same reason.
vi.mock('@/lib/v2-calendar/month', async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>
  return {
    ...actual,
    fetchFortuneDays: vi.fn(async (_raw: unknown, month: string) => [
      { date: `${month}-05`, dayOfMonth: 5, dayGanzhi: '甲子', overallPercent: 70, grade: 'B+' },
    ]),
    fetchAlmanacDays: vi.fn(async () => []),
  }
})
vi.mock('@/lib/v2-calendar/day-detail', async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>
  return {
    ...actual, // pickFreeDayDetail stays REAL — the trim is what tells the two verdicts apart
    mapDayDetail: vi.fn(() => ({
      date: '2029-01-05', dayGanzhi: '甲子', overallPercent: 71, grade: 'B+', verdict: 'ดี',
      summary: 'ส', suitable: [], avoid: [], insight: 'PAID', compatAreas: [], advice: [],
      yams: [], dithi: { officer: 'o', officerDesc: 'PAID', jianchu: 'PAID' }, luckyDirection: 'N',
      dayDeity: 'เทพ', spirits: [], wanPhra: { isWanPhra: false, label: '' },
      dayPillars: { day: null, month: null, year: null }, ownerPillars: {}, gates: [], colors: [],
    })),
  }
})
global.fetch = vi.fn(async () => ({ ok: true, json: async () => ({}) }) as unknown as Response) as unknown as typeof fetch

import monthHandler from '@/pages/api/v2/calendar-month'
import dayHandler from '@/pages/api/v2/day-detail'

const PERSON = { dob: '1990-01-01', time: '08:00', gender: 'male', isRememberTime: true }
let n = 0

function makeRes() {
  const res: { statusCode: number; body: any; status: any; json: any } = {
    statusCode: 0, body: undefined,
    status: vi.fn((c: number) => ((res.statusCode = c), res)),
    json: vi.fn((b: unknown) => ((res.body = b), res)),
  }
  return res
}

/** The MONTH gate's verdict for this user, read off the real response. */
async function monthAllows(userId: string) {
  h.who = { ok: true, userId }
  const res = makeRes()
  // a fresh month per call so the route's per-(user, month) cache never answers for a previous case
  await monthHandler({ method: 'POST', body: { person: PERSON, month: `2029-${String((n++ % 12) + 1).padStart(2, '0')}` } } as never, res as never)
  return res.body?.allowed === true
}

/** The DAY gate's verdict for the same user. 🔴 Read from what the response CONTAINS, not from a status
 *  code: this route answers 200 to everyone and trims the paid fields instead (#226). */
async function dayAllows(userId: string) {
  h.who = { ok: true, userId }
  const res = makeRes()
  await dayHandler({ method: 'POST', body: { person: PERSON, date: `2029-01-${String((n++ % 20) + 5).padStart(2, '0')}` } } as never, res as never)
  return 'insight' in (res.body?.detail ?? {})
}

describe('#358 Phase 2 — both calendar gates decide from ONE source', () => {
  beforeEach(() => {
    h.memberPaymentValid = new Set()
    h.liveV2Row = new Set()
    h.undetermined = new Set()
    n += 37 // push the cache keys well clear of the previous case
    vi.clearAllMocks()
  })

  // ① THE TABLE. Every combination of the two stores, both gates, one assertion: they agree.
  const CASES = [
    { name: 'neither store has a row', pay: false, v2: false, expected: false },
    { name: 'member_payment only — the legacy member', pay: true, v2: false, expected: true },
    { name: '🔴 member_subscription only — THE DIVERGENT STATE', pay: false, v2: true, expected: true },
    { name: 'both rows — what the settle path actually writes', pay: true, v2: true, expected: true },
  ]

  for (const c of CASES) {
    it(`① ${c.name} — the month gate and the day gate answer the same`, async () => {
      const u = `U-${c.pay ? 'P' : ''}${c.v2 ? 'V' : ''}-${Math.random().toString(36).slice(2, 8)}`
      if (c.pay) h.memberPaymentValid.add(u)
      if (c.v2) h.liveV2Row.add(u)

      const month = await monthAllows(u)
      const day = await dayAllows(u)
      expect(month, `month=${month} day=${day}`).toBe(day)
      expect(month).toBe(c.expected)
    })
  }

  // ② 🔴 The table above passes trivially if BOTH gates refuse everyone. This is the pole that stops that:
  //    two users in the same run, one paid and one not, must come out different at BOTH gates.
  //    🔴 The paid user here holds a member_payment row, NOT a v2 row, on purpose. The first draft used a
  //    v2 row — which is the divergent state itself — so this control reddened under MP1 alongside the case
  //    it was supposed to be independent of, and could not have told "the gates stopped separating anyone"
  //    apart from "the divergent row moved". A control that fails with the thing it controls for is not one.
  it('② CONTROL — the gates still separate a paying user from a free one, at both routes', async () => {
    const paid = 'U-CTRL-PAID'
    const free = 'U-CTRL-FREE'
    h.memberPaymentValid.add(paid)
    expect(await monthAllows(paid)).toBe(true)
    expect(await dayAllows(paid)).toBe(true)
    expect(await monthAllows(free)).toBe(false)
    expect(await dayAllows(free)).toBe(false)
  })

  // ③ 🔴 MP2 — `isPaid` is boolean | null, and null means a v2 row carried a tier_code we refused to map.
  //    Before Phase 2 the month gate read a boolean `isFree` and had no way to express this state at all.
  //    Both gates must now fail CLOSED on it, and for the same reason.
  it('③ an undetermined tier is refused by BOTH gates — null is not paid', async () => {
    const u = 'U-UNDETERMINED'
    h.undetermined.add(u)
    expect(await monthAllows(u)).toBe(false)
    expect(await dayAllows(u)).toBe(false)
  })

  // ④ The store the month gate used to read alone must no longer be able to answer for it on its own.
  //    This is the same fact as the ① divergent row, stated as the negative: member_payment absent, and
  //    the month gate still says yes.
  it('④ the month gate no longer needs a member_payment row to say yes', async () => {
    const u = 'U-V2-ONLY-NEG'
    h.liveV2Row.add(u)
    expect(h.memberPaymentValid.has(u), 'the fixture really has no legacy row').toBe(false)
    expect(await monthAllows(u)).toBe(true)
  })
})
