// #358 Phase 2 — the two calendar gates decide from ONE source.
//
// ANCHOR: scripts/calendar-gates-one-source.test.tsx#both-calendar-gates-agree-for-every-store-state
// Bug-class this owns: one feature, two server gates, two different stores. `pages/api/v2/day-detail.ts:82`
// has always asked `resolveSubscription` (member_subscription first, member_payment as the fallback);
// `pages/api/v2/calendar-month.ts` asked `resolveMembership` (member_payment and nothing else). Nothing in
// the codebase ever compared their answers, so the split was invisible from every direction: the board has
// no state for it, both routes had green tests, and no user was affected.
//
// 🔴 THE SHAPE OF THE TEST IS THE POINT. The stubs below model the two STORES — a member_subscription row
// and a member_payment row — and the two resolvers are reconstructed on top of them exactly as the real
// ones read them (lib/usage.ts:27 reads one table; lib/v2/subscription.ts:220-243 reads the other and then
// falls back to the first). The assertion is then AGREEMENT across every combination, which means the
// divergent state is GENERATED by the fixture rather than asserted by me. A test that hard-coded
// "v2-row-only ⇒ allowed" would be my belief about the resolvers wearing a green tick.
//
// ⚠️ WHAT THIS DOES NOT PROVE, and what does. The premise — that the real resolvers read the two stores
// this way — is modelled here, not measured here. It is measured against real postgres in
// `scripts/member-subscription-db.test.ts` ("#358 Phase 2 — the premise"), which is DB-gated and does not
// run in this lane. If those two files ever disagree, the DB one is right.
//
// 🔴 MUTANT CONTRACT (each reddens `npm test`):
//   Re-fired 2026-08-29 against the committed baseline after ⑥ was added. Every count below is from a run.
//   MP1  calendar-month goes back to resolveMembership   → ① v2-row-only + ④ + ⑤ + ⑥  (4 of 9)
//        The other three rows of ① stay green, which is what makes it the DIVERGENT state rather than a
//        blanket failure. ⑤ and ⑥ redden because they pin the two directions where main ALLOWED and this
//        branch refuses — restoring main's resolver is exactly what must break them.
//   MP2  calendar-month reads `isPaid` loosely (`!== false` instead of `=== true`)  → ③ + ⑤  (2 of 9)
//        ⑥ stays GREEN here, and that is the useful part: a FREE row answers isPaid `false`, not null, so
//        a loose null-read cannot rescue it. ⑤ and ⑥ are different bugs and this separates them.
//   ⚠️ THESE COUNTS PREDATE mojisejr/mootech-fe#525 (merged 20c0b09), which reversed ⑥ from asserting the
//        loss to asserting the fix. Whoever re-fires MP1/MP2/MP3 must re-measure rather than trust the
//        numbers above — a count taken before a case changed meaning is not a count of the same thing.
//   MP3  day-detail goes to resolveMembership instead     → ① + ⑤ + ⑥  (3 of 9), reddening from the other
//        side and proving the table watches both routes, not just the one that changed.
//
// 🔴 HOW THIS TABLE WAS FILLED IN, because it matters more than the numbers. It has now been re-measured
// twice, because both times a new case moved counts I would otherwise have left stale. On the first pass I
// typed the new counts from reasoning and then fired: MP2 matched, MP1 and MP3 did not. Nothing here is a
// prediction, and the places where my prediction lost to the run are written down rather than overwritten.
import { describe, it, expect, vi, beforeEach } from 'vitest'

const h = vi.hoisted(() => ({
  who: { ok: true, userId: 'U' } as { ok: true; userId: string } | { ok: false; status: 401; error: string },
  // THE STORES. Everything below is derived from these two sets, never set directly.
  memberPaymentValid: new Set<string>(),
  liveV2Row: new Set<string>(),
  /** set to force the undetermined verdict — a v2 row whose tier_code we refused to understand. */
  undetermined: new Set<string>(),
  /** a LIVE v2 row whose tier is FREE. Maps cleanly, passes 0006's CHECK, and is not paid.
   *  ⇒ mojisejr/mootech-fe#525. Kept separate from `undetermined` because the CHECK stops that one
   *  and does not stop this one, which is the whole difference that matters. */
  freeV2Row: new Set<string>(),
}))

vi.mock('@/lib/v2/resolve-user', () => ({ resolveSessionUserId: vi.fn(async () => h.who) }))
// #358 Phase 3 — this suite asks whether the two gates AGREE, which is a different question from how far
// each level may scroll. Its months walk 2029-xx for cache isolation, so "now" is pinned there and its
// paid verdicts are PRO (no wall). If the span ever became what decides a row here, the agreement being
// measured would silently become an agreement about the span instead.
vi.mock('@/lib/v2/clock', () => ({ currentMonthBkk: () => '2029-01' }))

// lib/usage.ts:27 — one table, one row, classify. Nothing else.
vi.mock('@/lib/usage', () => ({
  resolveMembership: vi.fn(async (userId: string) => ({
    isFree: !h.memberPaymentValid.has(userId),
    reason: h.memberPaymentValid.has(userId) ? 'MEMBER' : 'NO_PLAN',
    memberPayment: null,
  })),
}))

// lib/v2/subscription.ts:220-243 — the v2 rows decide when one is live; otherwise the legacy verdict.
// 🔴 THE STUB CALLS THE REAL RULE. It used to restate it, and the copy went stale the moment
// mojisejr/mootech-fe#525 shipped: it said "a live row wins outright and the legacy branch is never
// consulted" and answered `FREE` regardless of the legacy row — which was true when written and became
// the defect #525 removed. Every case in this file then asserted against a resolver the app no longer
// had, and NOTHING here went red to say so. I found it by grepping the class of claim after that merge,
// not by anything failing.
//
// So the stub now builds the two INPUTS from the fixture and hands them to the actual
// `resolveTierFromSources` (pure, no I/O — importOriginal reaches it past this very mock). What stays
// local is only which rows this user has; the RULE cannot drift again, because there is no second copy.
// A mutant in that rule now reddens this file too, which was the whole point.
//
// ⚠️ THE COPY MOVED UP A LEVEL, IT DID NOT DISAPPEAR (ตู๋). The rule has one copy now; the INPUTS the rule
// receives are still assembled by hand here, and that hand-written part is the same shape as the thing
// that just rotted, one function higher. Concretely: this stub ALWAYS passes a legacy verdict, while the
// real `resolveSubscription` decides whether to read `member_payment` at all (`decidesWithoutLegacy`) and
// passes `NO_LEGACY` when it does not. So the stub is more generous than production, and the branch that
// chooses between those two has NO representative in this file.
// ⇒ measured, not feared: reverting that call site to a bare `if (live)` leaves this file 9/9 green while
//   scripts/member-subscription.test.ts goes red on two cases. Not a hole — that half is the OTHER file's
//   subject and is watched there, which is the right place for it. Named here so nobody reads
//   "no second copy" as "nothing left to drift".
//
// 🔑 AND THE LINE THIS TECHNIQUE MUST NOT CROSS: the expected values below stay LITERALS. They are never
// computed from the rule. That is exactly why a mutant in the rule can redden this file — a spec that
// derived its expectations from the rule would agree with any rule, including a broken one.
vi.mock('@/lib/v2/subscription', async (importOriginal) => {
  const actual = (await importOriginal()) as typeof import('@/lib/v2/subscription')
  return {
    ...actual,
    resolveSubscription: vi.fn(async (userId: string) => {
      // the fixture's rows, expressed as the resolver's own two inputs
      const subRow = h.undetermined.has(userId)
        ? { tierCode: 'PLATINUM' } // a code the allow-list refuses — the undetermined case
        : h.freeV2Row.has(userId)
          ? { tierCode: 'FREE' }
          : h.liveV2Row.has(userId)
            ? { tierCode: 'PRO' }
            : null
      const legacyPaid = h.memberPaymentValid.has(userId)
      const verdict = actual.resolveTierFromSources({
        subRow,
        legacy: { isFree: !legacyPaid, reason: legacyPaid ? 'MEMBER' : 'NO_PLAN' },
      })
      return { ...verdict, expireAt: null }
    }),
  }
})

// Only the upstream network is stubbed. The entitlement table is deliberately NOT mocked, so this
// exercises the values that actually ship — the same choice scripts/calendar-month-gate-closed.tsx makes,
// and for the same reason. (Before #358 Phase 4 the unmocked thing named here was the gate switch,
// lib/v2-calendar/gate, which no longer exists.)
vi.mock('@/lib/v2-calendar/month', async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>
  return {
    ...actual,
    fetchFortuneDays: vi.fn(async (_raw: unknown, month: string) => [
      { date: `${month}-05`, dayOfMonth: 5, dayGanzhi: '甲子', overallPercent: 70, grade: 'B+' },
    ]),
    fetchAlmanacDays: vi.fn(async () => []),
  }
})
vi.mock('@/lib/v2-calendar/day-detail', async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>
  return {
    ...actual, // pickFreeDayDetail stays REAL — the trim is what tells the two verdicts apart
    mapDayDetail: vi.fn(() => ({
      date: '2029-01-05', dayGanzhi: '甲子', overallPercent: 71, grade: 'B+', verdict: 'ดี',
      summary: 'ส', suitable: [], avoid: [], insight: 'PAID', compatAreas: [], advice: [],
      yams: [], dithi: { officer: 'o', officerDesc: 'PAID', jianchu: 'PAID' }, luckyDirection: 'N',
      dayDeity: 'เทพ', spirits: [], wanPhra: { isWanPhra: false, label: '' },
      dayPillars: { day: null, month: null, year: null }, ownerPillars: {}, gates: [], colors: [],
    })),
  }
})
global.fetch = vi.fn(async () => ({ ok: true, json: async () => ({}) }) as unknown as Response) as unknown as typeof fetch

import monthHandler from '@/pages/api/v2/calendar-month'
import dayHandler from '@/pages/api/v2/day-detail'

const PERSON = { dob: '1990-01-01', time: '08:00', gender: 'male', isRememberTime: true }
let n = 0

function makeRes() {
  const res: { statusCode: number; body: any; status: any; json: any } = {
    statusCode: 0, body: undefined,
    status: vi.fn((c: number) => ((res.statusCode = c), res)),
    json: vi.fn((b: unknown) => ((res.body = b), res)),
  }
  return res
}

/** The MONTH gate's verdict for this user, read off the real response. */
async function monthAllows(userId: string) {
  h.who = { ok: true, userId }
  const res = makeRes()
  // a fresh month per call so the route's per-(user, month) cache never answers for a previous case
  await monthHandler({ method: 'POST', body: { person: PERSON, month: `2029-${String((n++ % 12) + 1).padStart(2, '0')}` } } as never, res as never)
  return res.body?.allowed === true
}

/** The DAY gate's verdict for the same user. 🔴 Read from what the response CONTAINS, not from a status
 *  code: this route answers 200 to everyone and trims the paid fields instead (#226). */
async function dayAllows(userId: string) {
  h.who = { ok: true, userId }
  const res = makeRes()
  await dayHandler({ method: 'POST', body: { person: PERSON, date: `2029-01-${String((n++ % 20) + 5).padStart(2, '0')}` } } as never, res as never)
  return 'insight' in (res.body?.detail ?? {})
}

describe('#358 Phase 2 — both calendar gates decide from ONE source', () => {
  beforeEach(() => {
    h.memberPaymentValid = new Set()
    h.liveV2Row = new Set()
    h.undetermined = new Set()
    h.freeV2Row = new Set()
    n += 37 // push the cache keys well clear of the previous case
    vi.clearAllMocks()
  })

  // ① THE TABLE. Every combination of the two stores, both gates, one assertion: they agree.
  const CASES = [
    { name: 'neither store has a row', pay: false, v2: false, expected: false },
    { name: 'member_payment only — the legacy member', pay: true, v2: false, expected: true },
    { name: '🔴 member_subscription only — THE DIVERGENT STATE', pay: false, v2: true, expected: true },
    { name: 'both rows — what the settle path actually writes', pay: true, v2: true, expected: true },
  ]

  for (const c of CASES) {
    it(`① ${c.name} — the month gate and the day gate answer the same`, async () => {
      const u = `U-${c.pay ? 'P' : ''}${c.v2 ? 'V' : ''}-${Math.random().toString(36).slice(2, 8)}`
      if (c.pay) h.memberPaymentValid.add(u)
      if (c.v2) h.liveV2Row.add(u)

      const month = await monthAllows(u)
      const day = await dayAllows(u)
      expect(month, `month=${month} day=${day}`).toBe(day)
      expect(month).toBe(c.expected)
    })
  }

  // ② 🔴 The table above passes trivially if BOTH gates refuse everyone. This is the pole that stops that:
  //    two users in the same run, one paid and one not, must come out different at BOTH gates.
  //    🔴 The paid user here holds a member_payment row, NOT a v2 row, on purpose. The first draft used a
  //    v2 row — which is the divergent state itself — so this control reddened under MP1 alongside the case
  //    it was supposed to be independent of, and could not have told "the gates stopped separating anyone"
  //    apart from "the divergent row moved". A control that fails with the thing it controls for is not one.
  it('② CONTROL — the gates still separate a paying user from a free one, at both routes', async () => {
    const paid = 'U-CTRL-PAID'
    const free = 'U-CTRL-FREE'
    h.memberPaymentValid.add(paid)
    expect(await monthAllows(paid)).toBe(true)
    expect(await dayAllows(paid)).toBe(true)
    expect(await monthAllows(free)).toBe(false)
    expect(await dayAllows(free)).toBe(false)
  })

  // ③ 🔴 MP2 — `isPaid` is boolean | null, and null means a v2 row carried a tier_code we refused to map.
  //    Before Phase 2 the month gate read a boolean `isFree` and had no way to express this state at all.
  //    Both gates must now fail CLOSED on it, and for the same reason.
  it('③ an undetermined tier is refused by BOTH gates — null is not paid', async () => {
    const u = 'U-UNDETERMINED'
    h.undetermined.add(u)
    expect(await monthAllows(u)).toBe(false)
    expect(await dayAllows(u)).toBe(false)
  })

  // ⑤ 🔴 THE OTHER DIRECTION. ตู๋ measured this through both real handlers and it is the case that made the
  //    first draft of this PR's description false: a user with a VALID member_payment row who ALSO holds a
  //    live v2 row we cannot map answered { month: true, day: false } on main and { month: false, day:
  //    false } here. The month gate LOSES this calendar for them. Kept as a test rather than a sentence,
  //    because a sentence is what was wrong the first time.
  //    Not reachable on a database carrying lib/db/0006_member_subscription.sql:33 — its CHECK admits only
  //    FREE/PLUS/PRO and lib/v2/tier.ts:73 maps all three. ⚠️ ? unknown whether prod carries that CHECK.
  it('⑤ a legacy member whose v2 row cannot be mapped — both gates refuse, and the month gate used to allow', async () => {
    const u = 'U-LEGACY-PLUS-UNMAPPABLE'
    h.memberPaymentValid.add(u)
    h.undetermined.add(u) // the live v2 row wins over the legacy shadow, and it answers isPaid: null
    expect(await monthAllows(u)).toBe(false)
    expect(await dayAllows(u)).toBe(false)
    // the half that proves this is the DIVERGENT reading and not just "everything is refused":
    h.undetermined.delete(u)
    expect(await monthAllows(u), 'drop the unmappable row and the legacy member is served again').toBe(true)
  })

  // ⑥ The same loss through a value 0006's CHECK ADMITS: tier_code 'FREE' maps cleanly and is not paid
  //    (lib/v2/tier.ts:124), and a live row never consults the legacy branch (lib/v2/subscription.ts:211),
  //    so a paying legacy member is cancelled by a FREE row. ลามุน photographed it: grid on d8643c3,
  //    nothing on this branch, header still reading "สมาชิก".
  //
  //    🔴 IT IS NOT REACHABLE BY PURCHASE, and I called it reachable twice before checking the write path.
  //    lib/payment/catalog.ts:78-80 throws UnsellablePackageError for a FREE tier BEFORE pricing, AFTER the
  //    isActive check — so activating one of the 6 FREE-tier catalogue rows does not sell it either.
  //    scripts/payment-catalog.test.ts:30 pins that with an isActive:true FREE row, and ตู๋ proved the pin
  //    has teeth by deleting the `|| tierCode === 'FREE'` clause and watching it redden.
  //    lib/payment/repo.ts:729 is the ONLY insert into member_subscription outside tests (grepped over
  //    lib pages features harness), so the row can only arrive by hand or by ops.
  //
  //    🔴 This test still asserts TODAY's behaviour, which is a LOSS, and it is not the behaviour we want —
  //    the resolver is willing to downgrade a known-paid member, which lib/v2/subscription.ts:55 says it
  //    intends never to do. mojisejr/mootech-fe#525 holds the decision. When that is fixed this test flips,
  //    and it flipping is the point: it is the guard that catches the fix landing.
  // 🔴 ⑥ REVERSED by mojisejr/mootech-fe#525 (merged 20c0b09). It used to assert the LOSS — that a paying
  // legacy member holding a live FREE row was refused BOTH calendar routes — and it named #525 as the
  // ticket that owned the regression. That ticket is now closed and the behaviour is the opposite: a live
  // KNOWN-not-paid row falls through to the legacy verdict instead of shadowing it.
  //
  // ⚠️ Left as a reversal rather than deleted. This pair of routes is the exact place the two gates
  // disagreed before Phase 2, so the case that proved they BOTH refuse is the case that should now prove
  // they BOTH serve — same user, same fixture, opposite expectation. Deleting it would remove the only
  // spec in this file that exercises a member with rows in both stores at once.
  it('⑥ a paying legacy member with a live FREE v2 row KEEPS the month (#525)', async () => {
    const u = 'U-LEGACY-SHADOWED-BY-FREE'
    h.memberPaymentValid.add(u)
    h.freeV2Row.add(u)
    expect(await monthAllows(u), 'the FREE row must not cancel a paid legacy membership').toBe(true)
    expect(await dayAllows(u), 'and the day gate agrees — one resolver, one answer').toBe(true)
    // 🔴 the teeth: this must be the LEGACY row talking, not the fixture serving everybody. Take the
    // paid legacy row away, leave the FREE row in place, and the same user must lose the month.
    h.memberPaymentValid.delete(u)
    expect(await monthAllows(u), 'a FREE row with nothing paid behind it is still free').toBe(false)
    expect(await dayAllows(u), 'both routes agree in that direction too').toBe(false)
  })

  // ④ The store the month gate used to read alone must no longer be able to answer for it on its own.
  //    This is the same fact as the ① divergent row, stated as the negative: member_payment absent, and
  //    the month gate still says yes.
  it('④ the month gate no longer needs a member_payment row to say yes', async () => {
    const u = 'U-V2-ONLY-NEG'
    h.liveV2Row.add(u)
    expect(h.memberPaymentValid.has(u), 'the fixture really has no legacy row').toBe(false)
    expect(await monthAllows(u)).toBe(true)
  })
})
